// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v1/metrics.proto

package com.bonree.integration.core.opentelemetry.metrics.v1;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030metrics/v1/metrics.proto\022\036opentelemetr" +
      "y.proto.metrics.v1\032\026common/v1/common.pro" +
      "to\032\032resource/v1/resource.proto\"X\n\013Metric" +
      "sData\022I\n\020resource_metrics\030\001 \003(\0132/.opente" +
      "lemetry.proto.metrics.v1.ResourceMetrics" +
      "\"\257\001\n\017ResourceMetrics\022;\n\010resource\030\001 \001(\0132)" +
      ".opentelemetry.proto.resource.v1.Resourc" +
      "e\022C\n\rscope_metrics\030\002 \003(\0132,.opentelemetry" +
      ".proto.metrics.v1.ScopeMetrics\022\022\n\nschema" +
      "_url\030\003 \001(\tJ\006\010\350\007\020\351\007\"\237\001\n\014ScopeMetrics\022B\n\005s" +
      "cope\030\001 \001(\01323.opentelemetry.proto.common." +
      "v1.InstrumentationScope\0227\n\007metrics\030\002 \003(\013" +
      "2&.opentelemetry.proto.metrics.v1.Metric" +
      "\022\022\n\nschema_url\030\003 \001(\t\"\222\003\n\006Metric\022\014\n\004name\030" +
      "\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\014\n\004unit\030\003 \001(\t" +
      "\0226\n\005gauge\030\005 \001(\0132%.opentelemetry.proto.me" +
      "trics.v1.GaugeH\000\0222\n\003sum\030\007 \001(\0132#.opentele" +
      "metry.proto.metrics.v1.SumH\000\022>\n\thistogra" +
      "m\030\t \001(\0132).opentelemetry.proto.metrics.v1" +
      ".HistogramH\000\022U\n\025exponential_histogram\030\n " +
      "\001(\01324.opentelemetry.proto.metrics.v1.Exp" +
      "onentialHistogramH\000\022:\n\007summary\030\013 \001(\0132\'.o" +
      "pentelemetry.proto.metrics.v1.SummaryH\000B" +
      "\006\n\004dataJ\004\010\004\020\005J\004\010\006\020\007J\004\010\010\020\t\"M\n\005Gauge\022D\n\013da" +
      "ta_points\030\001 \003(\0132/.opentelemetry.proto.me" +
      "trics.v1.NumberDataPoint\"\272\001\n\003Sum\022D\n\013data" +
      "_points\030\001 \003(\0132/.opentelemetry.proto.metr" +
      "ics.v1.NumberDataPoint\022W\n\027aggregation_te" +
      "mporality\030\002 \001(\01626.opentelemetry.proto.me" +
      "trics.v1.AggregationTemporality\022\024\n\014is_mo" +
      "notonic\030\003 \001(\010\"\255\001\n\tHistogram\022G\n\013data_poin" +
      "ts\030\001 \003(\01322.opentelemetry.proto.metrics.v" +
      "1.HistogramDataPoint\022W\n\027aggregation_temp" +
      "orality\030\002 \001(\01626.opentelemetry.proto.metr" +
      "ics.v1.AggregationTemporality\"\303\001\n\024Expone" +
      "ntialHistogram\022R\n\013data_points\030\001 \003(\0132=.op" +
      "entelemetry.proto.metrics.v1.Exponential" +
      "HistogramDataPoint\022W\n\027aggregation_tempor" +
      "ality\030\002 \001(\01626.opentelemetry.proto.metric" +
      "s.v1.AggregationTemporality\"P\n\007Summary\022E" +
      "\n\013data_points\030\001 \003(\01320.opentelemetry.prot" +
      "o.metrics.v1.SummaryDataPoint\"\206\002\n\017Number" +
      "DataPoint\022;\n\nattributes\030\007 \003(\0132\'.opentele" +
      "metry.proto.common.v1.KeyValue\022\034\n\024start_" +
      "time_unix_nano\030\002 \001(\006\022\026\n\016time_unix_nano\030\003" +
      " \001(\006\022\023\n\tas_double\030\004 \001(\001H\000\022\020\n\006as_int\030\006 \001(" +
      "\020H\000\022;\n\texemplars\030\005 \003(\0132(.opentelemetry.p" +
      "roto.metrics.v1.Exemplar\022\r\n\005flags\030\010 \001(\rB" +
      "\007\n\005valueJ\004\010\001\020\002\"\277\002\n\022HistogramDataPoint\022;\n" +
      "\nattributes\030\t \003(\0132\'.opentelemetry.proto." +
      "common.v1.KeyValue\022\034\n\024start_time_unix_na" +
      "no\030\002 \001(\006\022\026\n\016time_unix_nano\030\003 \001(\006\022\r\n\005coun" +
      "t\030\004 \001(\006\022\013\n\003sum\030\005 \001(\001\022\025\n\rbucket_counts\030\006 " +
      "\003(\006\022\027\n\017explicit_bounds\030\007 \003(\001\022;\n\texemplar" +
      "s\030\010 \003(\0132(.opentelemetry.proto.metrics.v1" +
      ".Exemplar\022\r\n\005flags\030\n \001(\r\022\013\n\003min\030\013 \001(\001\022\013\n" +
      "\003max\030\014 \001(\001J\004\010\001\020\002\"\233\004\n\035ExponentialHistogra" +
      "mDataPoint\022;\n\nattributes\030\001 \003(\0132\'.opentel" +
      "emetry.proto.common.v1.KeyValue\022\034\n\024start" +
      "_time_unix_nano\030\002 \001(\006\022\026\n\016time_unix_nano\030" +
      "\003 \001(\006\022\r\n\005count\030\004 \001(\006\022\013\n\003sum\030\005 \001(\001\022\r\n\005sca" +
      "le\030\006 \001(\021\022\022\n\nzero_count\030\007 \001(\006\022W\n\010positive" +
      "\030\010 \001(\0132E.opentelemetry.proto.metrics.v1." +
      "ExponentialHistogramDataPoint.Buckets\022W\n" +
      "\010negative\030\t \001(\0132E.opentelemetry.proto.me" +
      "trics.v1.ExponentialHistogramDataPoint.B" +
      "uckets\022\r\n\005flags\030\n \001(\r\022;\n\texemplars\030\013 \003(\013" +
      "2(.opentelemetry.proto.metrics.v1.Exempl" +
      "ar\022\013\n\003min\030\014 \001(\001\022\013\n\003max\030\r \001(\001\0320\n\007Buckets\022" +
      "\016\n\006offset\030\001 \001(\021\022\025\n\rbucket_counts\030\002 \003(\004\"\305" +
      "\002\n\020SummaryDataPoint\022;\n\nattributes\030\007 \003(\0132" +
      "\'.opentelemetry.proto.common.v1.KeyValue" +
      "\022\034\n\024start_time_unix_nano\030\002 \001(\006\022\026\n\016time_u" +
      "nix_nano\030\003 \001(\006\022\r\n\005count\030\004 \001(\006\022\013\n\003sum\030\005 \001" +
      "(\001\022Y\n\017quantile_values\030\006 \003(\0132@.openteleme" +
      "try.proto.metrics.v1.SummaryDataPoint.Va" +
      "lueAtQuantile\022\r\n\005flags\030\010 \001(\r\0322\n\017ValueAtQ" +
      "uantile\022\020\n\010quantile\030\001 \001(\001\022\r\n\005value\030\002 \001(\001" +
      "J\004\010\001\020\002\"\301\001\n\010Exemplar\022D\n\023filtered_attribut" +
      "es\030\007 \003(\0132\'.opentelemetry.proto.common.v1" +
      ".KeyValue\022\026\n\016time_unix_nano\030\002 \001(\006\022\023\n\tas_" +
      "double\030\003 \001(\001H\000\022\020\n\006as_int\030\006 \001(\020H\000\022\017\n\007span" +
      "_id\030\004 \001(\014\022\020\n\010trace_id\030\005 \001(\014B\007\n\005valueJ\004\010\001" +
      "\020\002*\214\001\n\026AggregationTemporality\022\'\n#AGGREGA" +
      "TION_TEMPORALITY_UNSPECIFIED\020\000\022!\n\035AGGREG" +
      "ATION_TEMPORALITY_DELTA\020\001\022&\n\"AGGREGATION" +
      "_TEMPORALITY_CUMULATIVE\020\002*;\n\016DataPointFl" +
      "ags\022\r\n\tFLAG_NONE\020\000\022\032\n\026FLAG_NO_RECORDED_V" +
      "ALUE\020\001B\222\001\n4com.bonree.integration.core.o" +
      "pentelemetry.metrics.v1B\014MetricsProtoP\001Z" +
      ")go.opentelemetry.io/proto/otlp/metrics/" +
      "v1\252\002\036OpenTelemetry.Proto.Metrics.V1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bonree.integration.core.opentelemetry.common.v1.CommonProto.getDescriptor(),
          com.bonree.integration.core.opentelemetry.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_MetricsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_MetricsData_descriptor,
        new String[] { "ResourceMetrics", });
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ResourceMetrics_descriptor,
        new String[] { "Resource", "ScopeMetrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ScopeMetrics_descriptor,
        new String[] { "Scope", "Metrics", "SchemaUrl", });
    internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_metrics_v1_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Metric_descriptor,
        new String[] { "Name", "Description", "Unit", "Gauge", "Sum", "Histogram", "ExponentialHistogram", "Summary", "Data", });
    internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_metrics_v1_Gauge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Gauge_descriptor,
        new String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_opentelemetry_proto_metrics_v1_Sum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Sum_descriptor,
        new String[] { "DataPoints", "AggregationTemporality", "IsMonotonic", });
    internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_opentelemetry_proto_metrics_v1_Histogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Histogram_descriptor,
        new String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogram_descriptor,
        new String[] { "DataPoints", "AggregationTemporality", });
    internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_opentelemetry_proto_metrics_v1_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Summary_descriptor,
        new String[] { "DataPoints", });
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_NumberDataPoint_descriptor,
        new String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "AsDouble", "AsInt", "Exemplars", "Flags", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_HistogramDataPoint_descriptor,
        new String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "BucketCounts", "ExplicitBounds", "Exemplars", "Flags", "Min", "Max", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor,
        new String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "Scale", "ZeroCount", "Positive", "Negative", "Flags", "Exemplars", "Min", "Max", });
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_ExponentialHistogramDataPoint_Buckets_descriptor,
        new String[] { "Offset", "BucketCounts", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor,
        new String[] { "Attributes", "StartTimeUnixNano", "TimeUnixNano", "Count", "Sum", "QuantileValues", "Flags", });
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor =
      internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_SummaryDataPoint_ValueAtQuantile_descriptor,
        new String[] { "Quantile", "Value", });
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_opentelemetry_proto_metrics_v1_Exemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_metrics_v1_Exemplar_descriptor,
        new String[] { "FilteredAttributes", "TimeUnixNano", "AsDouble", "AsInt", "SpanId", "TraceId", "Value", });
    com.bonree.integration.core.opentelemetry.common.v1.CommonProto.getDescriptor();
    com.bonree.integration.core.opentelemetry.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
