// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.dq.collector.change;

public interface ChangeFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .KeyValue keyValues = 1;</code>
   */
  java.util.List<KeyValue>
      getKeyValuesList();
  /**
   * <code>repeated .KeyValue keyValues = 1;</code>
   */
  KeyValue getKeyValues(int index);
  /**
   * <code>repeated .KeyValue keyValues = 1;</code>
   */
  int getKeyValuesCount();
  /**
   * <code>repeated .KeyValue keyValues = 1;</code>
   */
  java.util.List<? extends KeyValueOrBuilder>
      getKeyValuesOrBuilderList();
  /**
   * <code>repeated .KeyValue keyValues = 1;</code>
   */
  KeyValueOrBuilder getKeyValuesOrBuilder(
      int index);
}
