// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.dq.collector.change;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeyValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\"+\n\013ChangeField\022\034\n\tkeyValues" +
      "\030\001 \003(\0132\t.KeyValue\"&\n\010KeyValue\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\tB\033\n\027com.dq.collector.ch" +
      "angeP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChangeField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChangeField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeField_descriptor,
        new String[] { "KeyValues", });
    internal_static_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeyValue_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
