// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace/v1/trace.proto

package com.bonree.integration.core.opentelemetry.trace.v1;

public interface ResourceSpansOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentelemetry.proto.trace.v1.ResourceSpans)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource for the spans in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <pre>
   * The resource for the spans in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   * @return The resource.
   */
  com.bonree.integration.core.opentelemetry.resource.v1.Resource getResource();
  /**
   * <pre>
   * The resource for the spans in this message.
   * If this field is not set then no resource info is known.
   * </pre>
   *
   * <code>.opentelemetry.proto.resource.v1.Resource resource = 1;</code>
   */
  com.bonree.integration.core.opentelemetry.resource.v1.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <pre>
   * A list of ScopeSpans that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.ScopeSpans scope_spans = 2;</code>
   */
  java.util.List<ScopeSpans> 
      getScopeSpansList();
  /**
   * <pre>
   * A list of ScopeSpans that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.ScopeSpans scope_spans = 2;</code>
   */
  ScopeSpans getScopeSpans(int index);
  /**
   * <pre>
   * A list of ScopeSpans that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.ScopeSpans scope_spans = 2;</code>
   */
  int getScopeSpansCount();
  /**
   * <pre>
   * A list of ScopeSpans that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.ScopeSpans scope_spans = 2;</code>
   */
  java.util.List<? extends ScopeSpansOrBuilder> 
      getScopeSpansOrBuilderList();
  /**
   * <pre>
   * A list of ScopeSpans that originate from a resource.
   * </pre>
   *
   * <code>repeated .opentelemetry.proto.trace.v1.ScopeSpans scope_spans = 2;</code>
   */
  ScopeSpansOrBuilder getScopeSpansOrBuilder(
      int index);

  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_spans" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The schemaUrl.
   */
  String getSchemaUrl();
  /**
   * <pre>
   * This schema_url applies to the data in the "resource" field. It does not apply
   * to the data in the "scope_spans" field which have their own schema_url field.
   * </pre>
   *
   * <code>string schema_url = 3;</code>
   * @return The bytes for schemaUrl.
   */
  com.google.protobuf.ByteString
      getSchemaUrlBytes();
}
