// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace/v1/trace.proto

package com.bonree.integration.core.opentelemetry.trace.v1;

public final class TraceProto {
  private TraceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_TracesData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_TracesData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_ResourceSpans_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_ResourceSpans_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_ScopeSpans_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_ScopeSpans_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_Span_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_Span_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_Span_Link_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_Span_Link_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_opentelemetry_proto_trace_v1_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_opentelemetry_proto_trace_v1_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024trace/v1/trace.proto\022\034opentelemetry.pr" +
      "oto.trace.v1\032\026common/v1/common.proto\032\032re" +
      "source/v1/resource.proto\"Q\n\nTracesData\022C" +
      "\n\016resource_spans\030\001 \003(\0132+.opentelemetry.p" +
      "roto.trace.v1.ResourceSpans\"\247\001\n\rResource" +
      "Spans\022;\n\010resource\030\001 \001(\0132).opentelemetry." +
      "proto.resource.v1.Resource\022=\n\013scope_span" +
      "s\030\002 \003(\0132(.opentelemetry.proto.trace.v1.S" +
      "copeSpans\022\022\n\nschema_url\030\003 \001(\tJ\006\010\350\007\020\351\007\"\227\001" +
      "\n\nScopeSpans\022B\n\005scope\030\001 \001(\01323.openteleme" +
      "try.proto.common.v1.InstrumentationScope" +
      "\0221\n\005spans\030\002 \003(\0132\".opentelemetry.proto.tr" +
      "ace.v1.Span\022\022\n\nschema_url\030\003 \001(\t\"\346\007\n\004Span" +
      "\022\020\n\010trace_id\030\001 \001(\014\022\017\n\007span_id\030\002 \001(\014\022\023\n\013t" +
      "race_state\030\003 \001(\t\022\026\n\016parent_span_id\030\004 \001(\014" +
      "\022\014\n\004name\030\005 \001(\t\0229\n\004kind\030\006 \001(\0162+.opentelem" +
      "etry.proto.trace.v1.Span.SpanKind\022\034\n\024sta" +
      "rt_time_unix_nano\030\007 \001(\006\022\032\n\022end_time_unix" +
      "_nano\030\010 \001(\006\022;\n\nattributes\030\t \003(\0132\'.opente" +
      "lemetry.proto.common.v1.KeyValue\022 \n\030drop" +
      "ped_attributes_count\030\n \001(\r\0228\n\006events\030\013 \003" +
      "(\0132(.opentelemetry.proto.trace.v1.Span.E" +
      "vent\022\034\n\024dropped_events_count\030\014 \001(\r\0226\n\005li" +
      "nks\030\r \003(\0132\'.opentelemetry.proto.trace.v1" +
      ".Span.Link\022\033\n\023dropped_links_count\030\016 \001(\r\022" +
      "4\n\006status\030\017 \001(\0132$.opentelemetry.proto.tr" +
      "ace.v1.Status\032\214\001\n\005Event\022\026\n\016time_unix_nan" +
      "o\030\001 \001(\006\022\014\n\004name\030\002 \001(\t\022;\n\nattributes\030\003 \003(" +
      "\0132\'.opentelemetry.proto.common.v1.KeyVal" +
      "ue\022 \n\030dropped_attributes_count\030\004 \001(\r\032\235\001\n" +
      "\004Link\022\020\n\010trace_id\030\001 \001(\014\022\017\n\007span_id\030\002 \001(\014" +
      "\022\023\n\013trace_state\030\003 \001(\t\022;\n\nattributes\030\004 \003(" +
      "\0132\'.opentelemetry.proto.common.v1.KeyVal" +
      "ue\022 \n\030dropped_attributes_count\030\005 \001(\r\"\231\001\n" +
      "\010SpanKind\022\031\n\025SPAN_KIND_UNSPECIFIED\020\000\022\026\n\022" +
      "SPAN_KIND_INTERNAL\020\001\022\024\n\020SPAN_KIND_SERVER" +
      "\020\002\022\024\n\020SPAN_KIND_CLIENT\020\003\022\026\n\022SPAN_KIND_PR" +
      "ODUCER\020\004\022\026\n\022SPAN_KIND_CONSUMER\020\005\"\256\001\n\006Sta" +
      "tus\022\017\n\007message\030\002 \001(\t\022=\n\004code\030\003 \001(\0162/.ope" +
      "ntelemetry.proto.trace.v1.Status.StatusC" +
      "ode\"N\n\nStatusCode\022\025\n\021STATUS_CODE_UNSET\020\000" +
      "\022\022\n\016STATUS_CODE_OK\020\001\022\025\n\021STATUS_CODE_ERRO" +
      "R\020\002J\004\010\001\020\002B\212\001\n2com.bonree.integration.cor" +
      "e.opentelemetry.trace.v1B\nTraceProtoP\001Z\'" +
      "go.opentelemetry.io/proto/otlp/trace/v1\252" +
      "\002\034OpenTelemetry.Proto.Trace.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bonree.integration.core.opentelemetry.common.v1.CommonProto.getDescriptor(),
          com.bonree.integration.core.opentelemetry.resource.v1.ResourceProto.getDescriptor(),
        });
    internal_static_opentelemetry_proto_trace_v1_TracesData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_opentelemetry_proto_trace_v1_TracesData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_TracesData_descriptor,
        new String[] { "ResourceSpans", });
    internal_static_opentelemetry_proto_trace_v1_ResourceSpans_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_opentelemetry_proto_trace_v1_ResourceSpans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_ResourceSpans_descriptor,
        new String[] { "Resource", "ScopeSpans", "SchemaUrl", });
    internal_static_opentelemetry_proto_trace_v1_ScopeSpans_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_opentelemetry_proto_trace_v1_ScopeSpans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_ScopeSpans_descriptor,
        new String[] { "Scope", "Spans", "SchemaUrl", });
    internal_static_opentelemetry_proto_trace_v1_Span_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_opentelemetry_proto_trace_v1_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_Span_descriptor,
        new String[] { "TraceId", "SpanId", "TraceState", "ParentSpanId", "Name", "Kind", "StartTimeUnixNano", "EndTimeUnixNano", "Attributes", "DroppedAttributesCount", "Events", "DroppedEventsCount", "Links", "DroppedLinksCount", "Status", });
    internal_static_opentelemetry_proto_trace_v1_Span_Event_descriptor =
      internal_static_opentelemetry_proto_trace_v1_Span_descriptor.getNestedTypes().get(0);
    internal_static_opentelemetry_proto_trace_v1_Span_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_Span_Event_descriptor,
        new String[] { "TimeUnixNano", "Name", "Attributes", "DroppedAttributesCount", });
    internal_static_opentelemetry_proto_trace_v1_Span_Link_descriptor =
      internal_static_opentelemetry_proto_trace_v1_Span_descriptor.getNestedTypes().get(1);
    internal_static_opentelemetry_proto_trace_v1_Span_Link_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_Span_Link_descriptor,
        new String[] { "TraceId", "SpanId", "TraceState", "Attributes", "DroppedAttributesCount", });
    internal_static_opentelemetry_proto_trace_v1_Status_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_opentelemetry_proto_trace_v1_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_opentelemetry_proto_trace_v1_Status_descriptor,
        new String[] { "Message", "Code", });
    com.bonree.integration.core.opentelemetry.common.v1.CommonProto.getDescriptor();
    com.bonree.integration.core.opentelemetry.resource.v1.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
