// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/metrics/v1/metrics_service.proto

package com.bonree.integration.core.opentelemetry.collector.metrics.v1;

/**
 * Protobuf type {@code opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess}
 */
public final class ExportMetricsPartialSuccess extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess)
    ExportMetricsPartialSuccessOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExportMetricsPartialSuccess.newBuilder() to construct.
  private ExportMetricsPartialSuccess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExportMetricsPartialSuccess() {
    errorMessage_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExportMetricsPartialSuccess();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExportMetricsPartialSuccess(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rejectedDataPoints_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MetricsServiceProto.internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsPartialSuccess_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MetricsServiceProto.internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsPartialSuccess_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExportMetricsPartialSuccess.class, Builder.class);
  }

  public static final int REJECTED_DATA_POINTS_FIELD_NUMBER = 1;
  private long rejectedDataPoints_;
  /**
   * <pre>
   * The number of rejected data points.
   * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
   * request was fully accepted.
   * </pre>
   *
   * <code>int64 rejected_data_points = 1;</code>
   * @return The rejectedDataPoints.
   */
  @Override
  public long getRejectedDataPoints() {
    return rejectedDataPoints_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
  private volatile Object errorMessage_;
  /**
   * <pre>
   * A developer-facing human-readable message in English. It should be used
   * either to explain why the server rejected parts of the data during a partial
   * success or to convey warnings/suggestions during a full success. The message
   * should offer guidance on how users can address such issues.
   * error_message is an optional field. An error_message with an empty value
   * is equivalent to it not being set.
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  @Override
  public String getErrorMessage() {
    Object ref = errorMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A developer-facing human-readable message in English. It should be used
   * either to explain why the server rejected parts of the data during a partial
   * success or to convey warnings/suggestions during a full success. The message
   * should offer guidance on how users can address such issues.
   * error_message is an optional field. An error_message with an empty value
   * is equivalent to it not being set.
   * </pre>
   *
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  @Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    Object ref = errorMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rejectedDataPoints_ != 0L) {
      output.writeInt64(1, rejectedDataPoints_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rejectedDataPoints_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, rejectedDataPoints_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExportMetricsPartialSuccess)) {
      return super.equals(obj);
    }
    ExportMetricsPartialSuccess other = (ExportMetricsPartialSuccess) obj;

    if (getRejectedDataPoints()
        != other.getRejectedDataPoints()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REJECTED_DATA_POINTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRejectedDataPoints());
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExportMetricsPartialSuccess parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricsPartialSuccess parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricsPartialSuccess parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportMetricsPartialSuccess parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExportMetricsPartialSuccess parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportMetricsPartialSuccess parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExportMetricsPartialSuccess prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess)
      ExportMetricsPartialSuccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetricsServiceProto.internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsPartialSuccess_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetricsServiceProto.internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsPartialSuccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExportMetricsPartialSuccess.class, Builder.class);
    }

    // Construct using com.bonree.integration.core.opentelemetry.collector.metrics.v1.ExportMetricsPartialSuccess.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      rejectedDataPoints_ = 0L;

      errorMessage_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MetricsServiceProto.internal_static_opentelemetry_proto_collector_metrics_v1_ExportMetricsPartialSuccess_descriptor;
    }

    @Override
    public ExportMetricsPartialSuccess getDefaultInstanceForType() {
      return ExportMetricsPartialSuccess.getDefaultInstance();
    }

    @Override
    public ExportMetricsPartialSuccess build() {
      ExportMetricsPartialSuccess result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExportMetricsPartialSuccess buildPartial() {
      ExportMetricsPartialSuccess result = new ExportMetricsPartialSuccess(this);
      result.rejectedDataPoints_ = rejectedDataPoints_;
      result.errorMessage_ = errorMessage_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExportMetricsPartialSuccess) {
        return mergeFrom((ExportMetricsPartialSuccess)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExportMetricsPartialSuccess other) {
      if (other == ExportMetricsPartialSuccess.getDefaultInstance()) return this;
      if (other.getRejectedDataPoints() != 0L) {
        setRejectedDataPoints(other.getRejectedDataPoints());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExportMetricsPartialSuccess parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExportMetricsPartialSuccess) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long rejectedDataPoints_ ;
    /**
     * <pre>
     * The number of rejected data points.
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_data_points = 1;</code>
     * @return The rejectedDataPoints.
     */
    @Override
    public long getRejectedDataPoints() {
      return rejectedDataPoints_;
    }
    /**
     * <pre>
     * The number of rejected data points.
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_data_points = 1;</code>
     * @param value The rejectedDataPoints to set.
     * @return This builder for chaining.
     */
    public Builder setRejectedDataPoints(long value) {
      
      rejectedDataPoints_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of rejected data points.
     * A `rejected_&lt;signal&gt;` field holding a `0` value indicates that the
     * request was fully accepted.
     * </pre>
     *
     * <code>int64 rejected_data_points = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectedDataPoints() {
      
      rejectedDataPoints_ = 0L;
      onChanged();
      return this;
    }

    private Object errorMessage_ = "";
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return The errorMessage.
     */
    public String getErrorMessage() {
      Object ref = errorMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A developer-facing human-readable message in English. It should be used
     * either to explain why the server rejected parts of the data during a partial
     * success or to convey warnings/suggestions during a full success. The message
     * should offer guidance on how users can address such issues.
     * error_message is an optional field. An error_message with an empty value
     * is equivalent to it not being set.
     * </pre>
     *
     * <code>string error_message = 2;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess)
  }

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccess)
  private static final ExportMetricsPartialSuccess DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExportMetricsPartialSuccess();
  }

  public static ExportMetricsPartialSuccess getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportMetricsPartialSuccess>
      PARSER = new com.google.protobuf.AbstractParser<ExportMetricsPartialSuccess>() {
    @Override
    public ExportMetricsPartialSuccess parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExportMetricsPartialSuccess(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExportMetricsPartialSuccess> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExportMetricsPartialSuccess> getParserForType() {
    return PARSER;
  }

  @Override
  public ExportMetricsPartialSuccess getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

